[package]
name = "wldash"
version = "0.1.0"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

[profile.release]
lto = "fat"

[features]
default = [ "rcalc" ]
ivy = [ "libivy" ]
bc = []
rcalc = [ "rcalc_lib" ]

[dependencies]
smithay-client-toolkit = "0.6.3"
byteorder = "1.0"
rusttype = "0.7.7"
chrono = "0.4"
nix = "0.14"
memmap = "0.7"
os_pipe = "0.8.1"
wayland-client = { version = "0.23", features = ["dlopen"] }
wayland-protocols = { version = "0.23", features = ["client", "unstable_protocols"] }
libpulse-binding = { version = "2.6.0"}
dbus = "0.6"
atty = "0.2"
fuzzy-matcher = "0.2"
lazy_static = "1.3.0"
libivy = { git = "https://github.com/kennylevinsen/libivy.git", optional = true }
rcalc_lib = { version = "0.9.3", optional = true }
